default_config:

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include customize.yaml

# Split helpers by domain
input_boolean: !include helpers_booleans.yaml      # on/off flags for template lights
input_number:  !include helpers_numbers.yaml       # brightness, mireds, temps, power
input_select:  !include helpers_selects.yaml       # scene dropdowns per room

# Lights, covers, scenes (you already have lights.yaml & scenes.yaml)
light: !include lights.yaml
cover: !include covers.yaml        # NEW below
scene: !include scenes.yaml

# Automations to map select -> scene
automation: !include automations.yaml

script: !include scripts.yaml

template:
  - sensor:
      - name: "Entrance Hall Power"
        unique_id: sensor.power_entrance_hall_w
        unit_of_measurement: "W"
        state: "{{ states('input_number.power_entrance_hall_w') | int(0) }}"
      - name: "Reception Power"
        unique_id: sensor.power_reception_w
        unit_of_measurement: "W"
        state: "{{ states('input_number.power_reception_w') | int(0) }}"
      - name: "Hall GF Power"
        unique_id: sensor.power_hall_gf_w
        unit_of_measurement: "W"
        state: "{{ states('input_number.power_hall_gf_w') | int(0) }}"
      - name: "Library Power"
        unique_id: sensor.power_library_w
        unit_of_measurement: "W"
        state: "{{ states('input_number.power_library_w') | int(0) }}"
