# ===== Core =====
default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    wall-overview:
      mode: yaml
      filename: dashboards/wall_overview.yaml
      title: Campus Overview
      icon: mdi:home-lightning-bolt
    wall-entrance:
      mode: yaml
      filename: dashboards/wall_entrance.yaml
      title: Entrance Hall
      icon: mdi:door
      show_in_sidebar: false
    wall-reception:
      mode: yaml
      filename: dashboards/wall_reception.yaml
      title: Reception
      icon: mdi:sofa
      show_in_sidebar: false
    wall-hall-gf:
      mode: yaml
      filename: dashboards/wall_hall_gf.yaml
      title: Hallway GF
      icon: mdi:stairs
      show_in_sidebar: false
    wall-library:
      mode: yaml
      filename: dashboards/wall_library.yaml
      title: Library
      icon: mdi:bookshelf
      show_in_sidebar: false

# ===== Includes (alles uit één folder) =====
homeassistant:
  customize: !include packages/kennemer/customize.yaml

input_boolean: !include packages/kennemer/helpers_booleans.yaml
input_number: !include packages/kennemer/helpers_numbers.yaml
input_select: !include packages/kennemer/helpers_selects.yaml

cover: !include packages/kennemer/covers.yaml
light: !include packages/kennemer/lights.yaml
scene: !include packages/kennemer/scenes.yaml
script: !include packages/kennemer/scripts.yaml
automation: !include packages/kennemer/automations.yaml

template: !include packages/kennemer/template.yaml
