- platform: template
  covers:
    reception_blind:
      friendly_name: "Reception Blind"
      unique_id: cover.reception_blind
      position_template: "{{ states('input_number.fake_blind_reception_pos')|int(0) }}"
      open_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_reception_pos, value: 100 }
      close_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_reception_pos, value: 0 }
      stop_cover: []
      set_cover_position:
        service: input_number.set_value
        data:
          entity_id: input_number.fake_blind_reception_pos
          value: "{{ position }}"

    hall_gf_blind:
      friendly_name: "Hall GF Blind"
      unique_id: cover.hall_gf_blind
      position_template: "{{ states('input_number.fake_blind_hall_gf_pos')|int(0) }}"
      open_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_hall_gf_pos, value: 100 }
      close_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_hall_gf_pos, value: 0 }
      stop_cover: []
      set_cover_position:
        service: input_number.set_value
        data:
          entity_id: input_number.fake_blind_hall_gf_pos
          value: "{{ position }}"

    library_blind:
      friendly_name: "Library Blind"
      unique_id: cover.library_blind
      position_template: "{{ states('input_number.fake_blind_library_pos')|int(0) }}"
      open_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_library_pos, value: 100 }
      close_cover:
        service: input_number.set_value
        data: { entity_id: input_number.fake_blind_library_pos, value: 0 }
      stop_cover: []
      set_cover_position:
        service: input_number.set_value
        data:
          entity_id: input_number.fake_blind_library_pos
          value: "{{ position }}"
